# Generated by Django 4.1.7 on 2023-04-01 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='room_mates',
            field=models.ManyToManyField(blank=True, related_name='roommates', to=settings.AUTH_USER_MODEL),
        ),
    ]
